name: 'google-drive-upload-git-action'
description: 'Upload files to Google Drive'
author: 'Aditya Karnam Gururaj Rao'
branding:
  icon: 'archive'
  color: 'green'
inputs:
  credentials:
    description: 'the service account credentials encoded in base64'
    required: true
  filename:
    description: 'the name of the file you want to upload'
    required: true
  folderId:
    description: 'the Id of the parent folder you want to upload the file in'
    required: true
  name:
    description: 'what you want the file to be called in Google Drive'
    required: false
  overwrite:
    description: 'if you want to overwrite an existing file in Google Drive '
    required: false
  mimeType:
    description: 'file MimeType. If absent, Google Drive will attempt to automatically detect an appropriate value'
    required: false
  useCompleteSourceFilenameAsName:
    description: 'If true, the target file name will be the source filename and name parameter will be ignored'
    required: false
  namePrefix:
    description: 'Prefix to be added in filename'
    required: false
  deleteAll:
    description: 'Delete all files'
    required: false

runs:
  using: docker
  image: Dockerfile
