on: [push]

jobs:
  render_uml:
    runs-on: ubuntu-latest
    name: Render all diagrams
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Render arquitetura 1
        uses: ./.github/actions/render
        id: render_arquitetura_1
        with:
          args: '-v -tsvg diagrams/test.puml -o ./out/diagrams/'

      - name: Render arquitetura 2
        uses: ./.github/actions/render
        id: render_arquitetura_2
        with:
          args: '-v -tsvg diagrams/test2.puml -o ./out/diagrams/'

      - name: list files
        run: ls -lsR

      - name: Copy to google drive
        uses: ./.github/actions/googledrive
        with:
          credentials: ${{ secrets.DRIVEDOC_CREDENTIALS }}
          filename: "./diagrams/out/diagrams/System detailed.svg"
          name: "DOC_teste.svg"
          folderId: ${{ secrets.DRIVEDOC_FOLDERID }}
          overwrite: "true"
          mimeType: "image/svg+xml"

      - name: Copy to google drive
        uses: ./.github/actions/googledrive
        with:
          credentials: ${{ secrets.DRIVEDOC_CREDENTIALS }}
          filename: "./diagrams/out/diagrams/TestC4.svg"
          name: "DOC_teste2.svg"
          folderId: ${{ secrets.DRIVEDOC_FOLDERID }}
          overwrite: "true"
          mimeType: "image/svg+xml"
